C:\Users\gabe.ochoa\Dropbox\Projects\BattleBot\Vlad\FEA Studies\TorsionStudy-Study 1
C:\Users\gabe.ochoa\Dropbox\Projects\BattleBot\Vlad\FEA Studies\TorsionStudy-Study 1
C:\Users\gabe.ochoa\Dropbox\Projects\BattleBot\Vlad\FEA Studies\TorsionStudy-Study 1
C:\Users\gabe.ochoa\Dropbox\Projects\BattleBot\Vlad\FEA Studies\TorsionStudy-Study 1
C:\Users\gabe.ochoa\Dropbox\Projects\BattleBot\Vlad\FEA Studies\TorsionStudy-Study 1
